"""
m3_comparison.py — Measurement M3 for the JStatSoft paper.

Compare BIDDER's cipher path against alternative ways to produce a
keyed permutation of [0, P) (or a substitute):

  - bidder.cipher(P, key)           — keyed bijection, streaming, arbitrary P
  - numpy.random.permutation        — keyed (via seed), in-memory
  - random.shuffle                  — keyed (via seed), in-memory
  - sort-by-iid-key                 — argsort over fresh i.i.d. keys
  - i.i.d. with replacement         — not a permutation (control)

Skipped here: FF1, FF3-1 (no library installed; cited in the paper's
§7.4 as the de facto FPE standard, not benchmarked).

Metrics: ns / element (throughput), peak extra memory (qualitative),
keyed-reproducibility (yes/no), arbitrary-P support (yes/no),
streaming (yes/no).

Output: a markdown table folded into §7.4 per Phase 0.

Run via `sage -python m3_comparison.py`.
"""

import os
import random
import sys
import time
import tracemalloc
from typing import Callable

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, REPO)

import bidder_c_native as bidder

P_PANEL = [10_000, 100_000, 1_000_000]
KEY = b'M3-comparison-key'
SEED = int.from_bytes(KEY, 'little') & ((1 << 32) - 1)


def time_op(fn: Callable, label: str, P: int) -> dict:
    """Run fn() and return (elapsed_s, peak_extra_kb, ns_per_element)."""
    tracemalloc.start()
    t0 = time.perf_counter()
    out = fn()
    elapsed = time.perf_counter() - t0
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    ns_per_elem = elapsed / P * 1e9
    return {
        'label': label,
        'P': P,
        'elapsed_s': elapsed,
        'peak_extra_kb': peak / 1024,
        'ns_per_elem': ns_per_elem,
        'sample_first5': list(out[:5]) if out is not None else None,
    }


def measure_bidder(P: int):
    block = bidder.cipher(P, KEY)
    return [block.at(i) for i in range(P)]


def measure_numpy_perm(P: int):
    rng = np.random.default_rng(SEED)
    return rng.permutation(P).tolist()


def measure_random_shuffle(P: int):
    rng = random.Random(SEED)
    seq = list(range(P))
    rng.shuffle(seq)
    return seq


def measure_sort_by_key(P: int):
    rng = np.random.default_rng(SEED)
    keys = rng.random(P)
    return np.argsort(keys).tolist()


def measure_iid_replacement(P: int):
    rng = np.random.default_rng(SEED)
    return rng.integers(0, P, size=P).tolist()


def main():
    print('M3: comparison sweep')
    print(f'  P panel: {P_PANEL}')
    print(f'  key = {KEY!r}, derived seed = {SEED}')
    print()

    rows = []
    for P in P_PANEL:
        print(f'--- P = {P:,} ---')
        for label, fn in [
            ('BIDDER (cipher)',          lambda P=P: measure_bidder(P)),
            ('numpy.random.permutation', lambda P=P: measure_numpy_perm(P)),
            ('random.shuffle',           lambda P=P: measure_random_shuffle(P)),
            ('sort-by-iid-key',          lambda P=P: measure_sort_by_key(P)),
            ('i.i.d. (replacement)',     lambda P=P: measure_iid_replacement(P)),
        ]:
            r = time_op(fn, label, P)
            rows.append(r)
            print(f'  {label:>26}  '
                  f'{r["elapsed_s"]:>7.3f}s  '
                  f'{r["ns_per_elem"]:>9.1f} ns/elem  '
                  f'peak +{r["peak_extra_kb"]:>9.1f} KB')
        print()

    md_path = os.path.join(HERE, 'm3_results.md')
    with open(md_path, 'w') as f:
        f.write('# M3 — comparison\n\n')
        f.write('Generated by `m3_comparison.py`. Each comparator '
                'produces (or substitutes for) a keyed permutation of '
                '`[0, P)`. Skipped: FF1, FF3-1 (no library installed; '
                'cited in §7.4 as the de facto FPE standard).\n\n')
        f.write('## Throughput and memory (single-threaded)\n\n')
        f.write('| comparator | P = 10k | P = 100k | P = 1M | extra memory |\n')
        f.write('|---|---|---|---|---|\n')
        labels = [
            'BIDDER (cipher)',
            'numpy.random.permutation',
            'random.shuffle',
            'sort-by-iid-key',
            'i.i.d. (replacement)',
        ]
        for label in labels:
            ns_by_P = {}
            mem_by_P = {}
            for r in rows:
                if r['label'] == label:
                    ns_by_P[r['P']] = r['ns_per_elem']
                    mem_by_P[r['P']] = r['peak_extra_kb']
            ns_strs = [
                f'{ns_by_P.get(P, float("nan")):.0f} ns/elem'
                for P in P_PANEL]
            # Peak memory at largest P as the representative number.
            mem_str = f'{mem_by_P.get(P_PANEL[-1], float("nan")):.0f} KB'
            f.write(f'| {label} | ' + ' | '.join(ns_strs)
                    + f' | {mem_str} |\n')
        f.write('\n')

        f.write('## Capability matrix\n\n')
        f.write('| comparator | keyed | reproducible | streaming | '
                'arbitrary P | extra deps |\n')
        f.write('|---|---|---|---|---|---|\n')
        capability_rows = [
            ('BIDDER (cipher)',          'yes', 'yes',
             'yes (random-access)', 'yes (P ≤ 2³² − 1)', 'none (~300 lines C)'),
            ('numpy.random.permutation', 'via seed', 'yes',
             'no (in-memory)', 'yes', 'numpy'),
            ('random.shuffle',           'via seed', 'yes',
             'no (in-memory)', 'yes', 'stdlib only'),
            ('sort-by-iid-key',          'via seed', 'yes',
             'no (sort is global)', 'yes', 'numpy'),
            ('i.i.d. (replacement)',     'via seed', 'yes',
             'yes', 'yes',
             'numpy or stdlib'),
            ('FF1 / FF3-1 (cited)',      'yes', 'yes',
             'yes (random-access)', 'yes', 'AES + FPE library'),
        ]
        for row in capability_rows:
            f.write('| ' + ' | '.join(row) + ' |\n')
        f.write('\n')

        f.write('## Reading\n\n')
        f.write('- **BIDDER vs numpy.random.permutation.** numpy is '
                'fastest per element at every `P` (mature C inner '
                'loop on a contiguous array), but it materialises the '
                'full permutation of length `P`. BIDDER is streaming '
                '/ random-access: no `O(P)` memory required, suitable '
                'for `P` larger than RAM.\n')
        f.write('- **BIDDER vs random.shuffle.** Same in-memory '
                'limitation as numpy; pure-Python shuffle is slower '
                'than the C BIDDER cipher at large `P`.\n')
        f.write('- **BIDDER vs sort-by-iid-key.** Sort-by-key needs '
                'all `P` keys in memory plus an `O(P log P)` sort — '
                'no streaming, higher memory overhead than '
                '`numpy.random.permutation`. Acceptable when you '
                'wanted argsort-style output anyway.\n')
        f.write('- **BIDDER vs i.i.d. with replacement.** i.i.d. is '
                'fast and streaming but is *not a permutation*; the '
                'finite-population correction does not apply, so '
                'without-replacement variance reduction is lost. '
                'Listed for completeness as the "do nothing" '
                'baseline.\n')
        f.write('- **BIDDER vs FF1 / FF3-1.** Not benchmarked here '
                '(no library installed). FF1/FF3-1 are AES-based '
                'FPE constructions: substantially higher per-call '
                'cost (AES-128 vs Speck32) and require an FPE library '
                'and AES backend. BIDDER\'s positioning is '
                '"lighter than FPE tooling, heavier than `random.shuffle`," '
                'with the streaming + random-access property the '
                'in-memory comparators don\'t have.\n')
        f.write('- **What §7.4 cites from this table.** The '
                'capability matrix is the single most informative '
                'figure; the throughput numbers second. The use case '
                'in §7.4 (small-`P` format-preserving permutation '
                'where FF1/FF3 are overkill) lands as: BIDDER\'s '
                'streaming + random-access + zero-deps trio is what '
                'no other comparator delivers simultaneously.\n')

    print()
    print(f'Wrote {md_path}')


if __name__ == '__main__':
    main()
