"""
use_case_03_cross_validation.py — §7.3 reproducible cross-validation.

Demonstrates four properties simultaneously: reproducible folds (key
→ partition), exact fold sizes (⌊n/k⌋ or ⌈n/k⌉), streaming
assignment (no materialised permutation), arbitrary `n`.

Construction: fold(i) := ⌊BIDDER.cipher.at(i) · k / n⌋. Since the
cipher is a bijection of `[0, n)`, the multiset of `cipher.at(i)`
over `i = 0, ..., n-1` is exactly `{0, ..., n-1}`, so the fold
cardinalities are independent of which records land in which fold —
every fold has either ⌊n/k⌋ or ⌈n/k⌉ elements.

Comparator: SHA-256-based hash assignment, `fold(i) := H(i) mod k`,
where H is SHA-256 (deterministic, with cryptographic-quality
distribution). Reports max deviation across 1000 trials of varying
hash salts.

Output: replication/use_case_03_results.md.

Run via `.venv/bin/python replication/use_case_03_cross_validation.py`.
"""

import hashlib
import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)

import bidder_c_native as bidder


def bidder_fold_sizes(n: int, k: int, key: bytes) -> list[int]:
    block = bidder.cipher(n, key)
    sizes = [0] * k
    for i in range(n):
        sizes[(block.at(i) * k) // n] += 1
    return sizes


def hash_fold_sizes(n: int, k: int, salt: bytes) -> list[int]:
    sizes = [0] * k
    for i in range(n):
        h = hashlib.sha256(salt + i.to_bytes(8, 'little')).digest()
        sizes[int.from_bytes(h[:8], 'little') % k] += 1
    return sizes


def expected_fold_sizes(n: int, k: int) -> tuple[int, int]:
    return (n // k, math.ceil(n / k))


def max_deviation(sizes: list[int], n: int, k: int) -> int:
    target_lo, target_hi = expected_fold_sizes(n, k)
    return max(
        max(s - target_hi for s in sizes),
        max(target_lo - s for s in sizes),
        0,
    )


def measure_panel():
    panels = [
        (1000, 5),
        (10000, 7),
        (100000, 10),
        (1000000, 10),
        (1000000, 100),
    ]

    rows = []
    print('§7.3 reproducible cross-validation')
    print(f'  {"(n, k)":<14} {"⌊n/k⌋":>8} {"⌈n/k⌉":>8} {"BIDDER max dev":>14} {"hash max dev (max over 1000 trials)":>40}')
    for n, k in panels:
        # BIDDER: one key, fold sizes deterministic.
        bidder_sizes = bidder_fold_sizes(n, k, b'use_case_03-key-' + str((n, k)).encode())
        bidder_max_dev = max_deviation(bidder_sizes, n, k)

        # Hash baseline: 1000 trials with different salts; report max
        # deviation across trials. Sample only 100 trials at n=1M to
        # keep the budget tight.
        n_trials = 1000 if n <= 100_000 else 100
        worst = 0
        for t in range(n_trials):
            salt = b'salt-' + t.to_bytes(8, 'little')
            sizes = hash_fold_sizes(n, k, salt)
            worst = max(worst, max_deviation(sizes, n, k))

        target_lo, target_hi = expected_fold_sizes(n, k)
        rows.append({
            'n': n, 'k': k,
            'target_lo': target_lo, 'target_hi': target_hi,
            'bidder_max_dev': bidder_max_dev,
            'hash_max_dev_worst': worst,
            'hash_n_trials': n_trials,
        })
        print(f'  ({n:>7}, {k:>3}) {target_lo:>8} {target_hi:>8} '
              f'{bidder_max_dev:>14} {worst:>40} (over {n_trials} trials)')

    return rows


def write_markdown(rows, md_path):
    with open(md_path, 'w') as f:
        f.write('# §7.3 — Reproducible cross-validation, exact fold sizes\n\n')
        f.write('Generated by `replication/use_case_03_cross_validation.py`. '
                'Cipher-leveraged use case (§4.4 permutation contract '
                'is what\'s load-bearing; §3 substrate is unused).\n\n')
        f.write('Construction: `fold(i) := ⌊BIDDER.cipher.at(i) · k / n⌋`. '
                'Since the cipher is a bijection of `[0, n)` (§4.4), the '
                'set `{cipher.at(i) : i ∈ [0, n)}` equals `{0, …, n-1}` '
                'as a multiset. The fold cardinalities are therefore '
                'independent of which records land in which fold — '
                'every fold has either `⌊n/k⌋` or `⌈n/k⌉` elements.\n\n')

        f.write('## Fold-size deviation panel\n\n')
        f.write('Max deviation = max(|fold_size − target|) where target ∈ {⌊n/k⌋, ⌈n/k⌉}. BIDDER is the cipher; hash row is SHA-256-based bucket assignment, `fold(i) := SHA-256(salt || i) mod k`.\n\n')
        f.write('| (n, k) | ⌊n/k⌋ | ⌈n/k⌉ | BIDDER max dev | hash max dev (worst of trials) | hash n_trials |\n')
        f.write('|---|---|---|---|---|---|\n')
        for r in rows:
            f.write(f'| ({r["n"]:,}, {r["k"]}) | {r["target_lo"]:,} | '
                    f'{r["target_hi"]:,} | **{r["bidder_max_dev"]}** | '
                    f'{r["hash_max_dev_worst"]:,} | {r["hash_n_trials"]} |\n')
        f.write('\n')
        f.write('*BIDDER row: deviation is `0` when `k | n`, `1` when '
                '`k ∤ n` — fold sizes are tight by construction.* Hash row '
                'shows the worst deviation across the trial budget; the '
                'one-σ band is `sqrt(n · (1/k) · ((k-1)/k))` and the '
                'expected max over independent draws of the n / k '
                'multinomial scales as `O(sqrt(n log k / k²))`.\n\n')

        f.write('## Reading\n\n')
        f.write('- **Headline.** BIDDER\'s fold-size deviation is at '
                'most 1, by construction. Hash-based assignment can '
                'be off by hundreds at moderate `n` (binomial sampling '
                'noise) and grows as `sqrt(n)`. For applications where '
                'fold-size balance is load-bearing (balanced CV '
                'variance bounds, fairness audits, cross-implementation '
                'reproducibility where deviation patterns must not '
                'drift between hash functions), BIDDER\'s exact-by-'
                'construction guarantee is the difference.\n')
        f.write('- **Reproducibility.** Same key + same `(n, k)` → same '
                'partition. Different keys → different partitions of '
                'the same exact sizes.\n')
        f.write('- **Streaming.** `BIDDER.cipher.at(i)` is `O(1)` per '
                'record (§4.4 stateless contract); no materialised '
                'permutation of `[0, n)`. Workable at `n` larger than '
                'RAM, where `numpy.random.permutation(n)` is not.\n')
        f.write('- **Comparator note.** Hash-based bucket assignment '
                'is the simpler choice when `O(sqrt(n/k))` fold-size '
                'deviation is acceptable; `numpy.random.permutation(n)` '
                'with a seed plus contiguous partition matches BIDDER '
                'on exactness when the dataset fits in memory '
                '(streaming requirement is what BIDDER is for).\n')


def main():
    rows = measure_panel()
    md_path = os.path.join(HERE, 'use_case_03_results.md')
    write_markdown(rows, md_path)
    print()
    print(f'Wrote {md_path}')


if __name__ == '__main__':
    main()
