/*
 * bench_c.c — direct-from-C throughput benchmark for libbidder.
 *
 * Closes DEBTS.md D4: measures bidder_block_at and bidder_sawtooth_at
 * in a tight C loop with no ctypes / Python interpreter overhead.
 * Companion to M3 (materialise full permutation through the wrapper)
 * and M4 (single random-access call through the wrapper).
 *
 * Build (from bidder-stat/ root):
 *     cc -O2 -I. -Igenerator replication/bench_c.c libbidder.dylib \
 *        -o replication/bench_c
 *
 * Or via Makefile target:
 *     make bench-c
 *
 * Run:
 *     ./replication/bench_c           # human-readable to stdout
 *     ./replication/bench_c <out.md>  # also write markdown to <out.md>
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "bidder_root.h"

static double monotonic_ns(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec * 1e9 + (double)ts.tv_nsec;
}

static const uint64_t P_PANEL[] = {
    1000ULL,
    10000ULL,
    100000ULL,
    1000000ULL,
    10000000ULL,
    100000000ULL,
};
static const size_t P_PANEL_LEN = sizeof(P_PANEL) / sizeof(P_PANEL[0]);

static const uint64_t N_BENCH    = 1000000ULL;
static const uint64_t N_WARMUP   = 1000ULL;
static const uint64_t SAWTOOTH_N = 7ULL;
static const uint8_t  KEY[]      = "D4-c-direct-bench";

typedef struct {
    uint64_t    P;
    const char *backend;
    double      cipher_ns;
    double      sawtooth_ns;
    uint64_t    cipher_iters;
    uint64_t    sawtooth_iters;
} bench_row;

static double bench_cipher(uint64_t P, const char **backend_out, uint64_t *iters_out)
{
    bidder_block_ctx ctx;
    int rc = bidder_cipher_init(&ctx, P, KEY, sizeof(KEY) - 1);
    if (rc != BIDDER_ROOT_OK) {
        *backend_out = "init-failed";
        *iters_out = 0;
        return -1.0;
    }
    *backend_out = bidder_block_backend(&ctx);

    uint32_t out;
    uint32_t sink = 0;
    uint64_t warm = (P < N_WARMUP) ? P : N_WARMUP;
    for (uint64_t i = 0; i < warm; ++i) {
        bidder_block_at(&ctx, i, &out);
        sink ^= out;
    }

    uint64_t n = (P < N_BENCH) ? P : N_BENCH;
    double t0 = monotonic_ns();
    for (uint64_t i = 0; i < n; ++i) {
        bidder_block_at(&ctx, i, &out);
        sink ^= out;
    }
    double elapsed = monotonic_ns() - t0;

    if (sink == 0xdeadbeefU) {
        fprintf(stderr, "(sink hit: %u)\n", sink);
    }

    *iters_out = n;
    return elapsed / (double)n;
}

static double bench_sawtooth(uint64_t P, uint64_t *iters_out)
{
    nprime_sequence_ctx ctx;
    int rc = bidder_sawtooth_init(&ctx, SAWTOOTH_N, P);
    if (rc != BIDDER_ROOT_OK) {
        *iters_out = 0;
        return -1.0;
    }

    uint64_t out;
    uint64_t sink = 0;
    uint64_t warm = (P < N_WARMUP) ? P : N_WARMUP;
    for (uint64_t i = 0; i < warm; ++i) {
        bidder_sawtooth_at(&ctx, i, &out);
        sink ^= out;
    }

    uint64_t n = (P < N_BENCH) ? P : N_BENCH;
    double t0 = monotonic_ns();
    for (uint64_t i = 0; i < n; ++i) {
        bidder_sawtooth_at(&ctx, i, &out);
        sink ^= out;
    }
    double elapsed = monotonic_ns() - t0;

    if (sink == 0xdeadbeefULL) {
        fprintf(stderr, "(sink hit: %llu)\n", (unsigned long long)sink);
    }

    *iters_out = n;
    return elapsed / (double)n;
}

static void print_human(FILE *f, const bench_row *rows, size_t n_rows)
{
    fprintf(f, "D4: C-direct throughput (no ctypes / Python overhead)\n");
    fprintf(f, "    panel: ");
    for (size_t i = 0; i < n_rows; ++i) {
        fprintf(f, "%llu ", (unsigned long long)rows[i].P);
    }
    fprintf(f, "\n    key:   \"%s\"\n", (const char *)KEY);
    fprintf(f, "    N_BENCH = %llu, N_WARMUP = %llu, sawtooth n = %llu\n\n",
            (unsigned long long)N_BENCH,
            (unsigned long long)N_WARMUP,
            (unsigned long long)SAWTOOTH_N);

    fprintf(f, "%-14s  %-9s  %-22s  %-22s\n",
            "P", "backend", "cipher (ns/call)", "sawtooth (ns/call)");
    fprintf(f, "%-14s  %-9s  %-22s  %-22s\n",
            "------", "-------", "----------------", "------------------");
    for (size_t i = 0; i < n_rows; ++i) {
        fprintf(f, "%-14llu  %-9s  %-22.1f  %-22.1f\n",
                (unsigned long long)rows[i].P,
                rows[i].backend,
                rows[i].cipher_ns,
                rows[i].sawtooth_ns);
    }
}

static void write_markdown(const char *path, const bench_row *rows, size_t n_rows)
{
    FILE *f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "warning: could not open %s for writing\n", path);
        return;
    }

    fprintf(f, "# D4 — C-direct throughput\n\n");
    fprintf(f,
        "Generated by `replication/bench_c.c`. Closes DEBTS.md D4. "
        "Each cell is the mean ns / call after a %llu-iteration warmup, "
        "averaged over `N_BENCH = %llu` calls (or `P` when `P < N_BENCH`). "
        "No ctypes / Python interpreter overhead — direct from C against "
        "`libbidder.dylib`.\n\n",
        (unsigned long long)N_WARMUP, (unsigned long long)N_BENCH);
    fprintf(f, "**Workload (per §6.4 taxonomy): C-direct kernel.** This is "
               "workload (3) — `bidder_block_at` / `bidder_sawtooth_at` "
               "called from C in a tight loop, no ctypes, no Python. "
               "Compare against M4 (workload 1, single random-access call "
               "through the Python wrapper) to measure ctypes overhead; "
               "compare against M3 (workload 2, materialise full "
               "permutation through the wrapper) only after subtracting "
               "wrapper costs.\n\n");
    fprintf(f, "## Throughput (single-threaded)\n\n");
    fprintf(f, "| P | backend | cipher (ns/call) | sawtooth (ns/call) |\n");
    fprintf(f, "|---|---|---|---|\n");
    for (size_t i = 0; i < n_rows; ++i) {
        fprintf(f, "| %llu | %s | %.1f | %.1f |\n",
                (unsigned long long)rows[i].P,
                rows[i].backend,
                rows[i].cipher_ns,
                rows[i].sawtooth_ns);
    }
    fprintf(f, "\n");

    double feistel_sum = 0.0, speck_sum = 0.0, saw_sum = 0.0;
    size_t feistel_n = 0, speck_n = 0, saw_n = 0;
    for (size_t i = 0; i < n_rows; ++i) {
        if (rows[i].cipher_ns > 0 && rows[i].backend) {
            if (strcmp(rows[i].backend, "feistel") == 0) {
                feistel_sum += rows[i].cipher_ns; ++feistel_n;
            } else if (strcmp(rows[i].backend, "speck32") == 0) {
                speck_sum += rows[i].cipher_ns; ++speck_n;
            }
        }
        if (rows[i].sawtooth_ns > 0) { saw_sum += rows[i].sawtooth_ns; ++saw_n; }
    }
    double feistel_avg = feistel_n ? (feistel_sum / (double)feistel_n) : 0.0;
    double speck_avg   = speck_n   ? (speck_sum   / (double)speck_n)   : 0.0;
    double saw_avg     = saw_n     ? (saw_sum     / (double)saw_n)     : 0.0;

    fprintf(f, "## §6.4 row\n\n");
    fprintf(f, "Per-backend numbers (C-direct cost is per-call constant-time "
               "within a backend; cycle-walking cost varies with `P` for "
               "Speck32 — see M1):\n\n");
    if (feistel_n) {
        fprintf(f, "- `bidder_block_at` (C-direct, Feistel, `P < 2^26`): "
                   "~%.0f ns/call (averaged over %zu panel points).\n",
                   feistel_avg, feistel_n);
    }
    if (speck_n) {
        fprintf(f, "- `bidder_block_at` (C-direct, Speck32 cycle-walking, "
                   "`P ≥ 2^26`): ~%.0f ns/call at this panel's "
                   "Speck32 point(s); cycle-walking ratio scales as "
                   "`2^32 / P`, so per-call cost varies — see M1.\n",
                   speck_avg);
    }
    fprintf(f, "- `bidder_sawtooth_at` (C-direct): ~%.0f ns/call (one "
               "divmod + arithmetic; backend-independent).\n\n", saw_avg);

    fprintf(f, "## Reading\n\n");
    fprintf(f, "- **Kernel cost is sub-µs.** Compared to M4's ~940 ns/elem "
               "for the cipher path through the Python wrapper, the "
               "C-direct number isolates the kernel from the ctypes "
               "round-trip. The ctypes overhead is the difference: "
               "M4_cipher_ns − bench_c_cipher_ns ≈ wrapper cost per call.\n");
    fprintf(f, "- **Backend matters.** The cycle-walking ratio bound "
               "(`MAX_CYCLE_WALK_RATIO = 64` → backend = `feistel` for "
               "`P < 2^26`) means the panel here uses Feistel for all "
               "small `P`. M1 covers the Speck32/64 regime at "
               "`P ≥ 2^26` and the cycle-walking-overhead curve.\n");
    fprintf(f, "- **§6.4 cites the C-direct row** as workload (3); §7.4's "
               "head-to-head comparison cites M3 as workload (2).\n");

    fclose(f);
    fprintf(stderr, "Wrote %s\n", path);
}

int main(int argc, char **argv)
{
    bench_row rows[16];
    if (P_PANEL_LEN > sizeof(rows) / sizeof(rows[0])) {
        fprintf(stderr, "panel too large for static buffer\n");
        return 1;
    }
    memset(rows, 0, sizeof(rows));

    for (size_t i = 0; i < P_PANEL_LEN; ++i) {
        uint64_t P = P_PANEL[i];
        const char *backend = "?";
        uint64_t citers = 0, siters = 0;
        double cipher_ns = bench_cipher(P, &backend, &citers);
        double saw_ns    = bench_sawtooth(P, &siters);
        rows[i].P = P;
        rows[i].backend = backend;
        rows[i].cipher_ns = cipher_ns;
        rows[i].sawtooth_ns = saw_ns;
        rows[i].cipher_iters = citers;
        rows[i].sawtooth_iters = siters;
    }

    print_human(stdout, rows, P_PANEL_LEN);

    if (argc >= 2) {
        write_markdown(argv[1], rows, P_PANEL_LEN);
    }

    return 0;
}
