"""
m2_feistel_domain.py — Map FPC realisation gap as a function of the
underlying Feistel domain s = ceil(sqrt(P)).

Mechanism: BIDDER's small-period backend is a balanced 8-round Feistel
on an s × s grid where s = isqrt_ceil(P) (see generator/bidder.c).
For P near s² the Feistel is exact-fit (no cycle-walking); as P drops
below s² toward (s-1)² + 1, cycle-walking rejects an increasing
fraction.

This script scans s = 15 .. 100, picking per-s probes:
  * exact-fit (P = s²): isolates the Feistel structure with no
    cycle-walking randomness.
  * mid-range (P ≈ s² - s): heavy cycle-walking from below.
  * lower edge (P = (s-1)² + 1): cycle-walking is at its maximum
    fraction (just barely needs s rather than s-1).

Reports ratio at N = P/2 only (the worst cell in the panel) plus
σ²-of-ratio sanity at one cell.
"""

import math
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)

import bidder_c_native as bidder

N_KEYS = 2000  # smaller per-cell budget; we have many cells
KEY_PREFIX = b'M2-domain-'


def f(x):
    return math.sin(math.pi * x)


def population_stats(P):
    vals = [f(k / P) for k in range(P)]
    R = sum(vals) / P
    sigma2 = sum((v - R) ** 2 for v in vals) / P
    return R, sigma2


def fpc_var(N, P, sigma2):
    if N >= P:
        return 0.0
    return sigma2 / N * (P - N) / (P - 1)


def measure(P, N, R, n_keys, key_tag):
    sumsq = 0.0
    for k in range(n_keys):
        key = KEY_PREFIX + key_tag + b'-' + k.to_bytes(8, 'little')
        block = bidder.cipher(P, key)
        s = 0.0
        for i in range(N):
            s += f(block.at(i) / P)
        d = s / N - R
        sumsq += d * d
    return sumsq / n_keys


def main():
    overall_t0 = time.perf_counter()

    # s grid: every s from 15 to 50, then sparse to 100.
    s_dense = list(range(15, 51))
    s_sparse = [55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
    s_list = s_dense + s_sparse

    rows = []  # (s, P_lower_edge, P_mid, P_exact_fit, ratios...)
    print(f's | s² | P_low | r_low | P_mid | r_mid | P_fit | r_fit')
    print('-' * 70)

    for s in s_list:
        P_fit = s * s
        P_mid = max(1, s * s - s)         # mid-range, heavy cycle-walk
        P_low = (s - 1) * (s - 1) + 1     # lower edge of this s

        # Sanity: each P_low should require exactly s, i.e.
        # ceil(sqrt(P_low)) == s.
        assert math.isqrt(P_low - 1) ** 2 < P_low <= P_fit

        results = {}
        for tag, P in [('low', P_low), ('mid', P_mid), ('fit', P_fit)]:
            N = max(1, P // 2)
            R, sigma2 = population_stats(P)
            t0 = time.perf_counter()
            measured = measure(P, N, R, N_KEYS,
                               f's{s}-{tag}'.encode())
            ideal = fpc_var(N, P, sigma2)
            ratio = measured / ideal if ideal > 0 else float('nan')
            results[tag] = (P, ratio, time.perf_counter() - t0)

        Pl, rl, tl = results['low']
        Pm, rm, tm = results['mid']
        Pf, rf, tf = results['fit']
        print(f'{s:3d} | {s*s:5d} | {Pl:5d} | {rl:6.3f} | '
              f'{Pm:5d} | {rm:6.3f} | {Pf:5d} | {rf:6.3f} | '
              f'({tl+tm+tf:.1f}s)')
        rows.append((s, Pl, rl, Pm, rm, Pf, rf))

    print(f'\nTotal: {time.perf_counter() - overall_t0:.1f}s')

    md_path = os.path.join(HERE, 'm2_feistel_domain_results.md')
    with open(md_path, 'w') as md:
        md.write('# M2 Feistel domain probe\n\n')
        md.write(f'Generated by `m2_feistel_domain.py`. n_keys = '
                 f'{N_KEYS} per cell. Integrand sin(πx). N = P/2 (the '
                 f'worst-case column from the baseline panel).\n\n')
        md.write('Feistel domain is s × s where s = ⌈√P⌉.\n\n')
        md.write('| s | s² | P_low (=(s-1)²+1) | ratio | '
                 'P_mid (=s²−s) | ratio | P_fit (=s²) | ratio |\n')
        md.write('|---|---|---|---|---|---|---|---|\n')
        for s, Pl, rl, Pm, rm, Pf, rf in rows:
            md.write(f'| {s} | {s*s} | {Pl} | {rl:.3f} | '
                     f'{Pm} | {rm:.3f} | {Pf} | {rf:.3f} |\n')
        md.write('\n')

    print(f'\nWrote {md_path}')


if __name__ == '__main__':
    main()
