"""
m2_power_of_two.py — Power-of-2 Feistel-domain probe.

Hypothesis (from m2_feistel_domain_results.md): when s = ⌈√P⌉ is a
power of 2, the F-function f = ((R+a) ⊕ b) mod L_size reduces (under
modulus 2^k) to a linear-ish operation that 8 Feistel rounds cannot
mix, producing prefix-mean variance far below ideal FPC.

Tests:
  * s ∈ {62..67}: characterise the s=64 (=2^6) neighbourhood and
    independently the s=65 dip seen in the wider sweep.
  * s ∈ {126..130}: characterise the s=128 (=2^7) neighbourhood —
    P_fit = 16384, just above the original panel's max P=10000.

For each s, three probes per the original m2_feistel_domain script:
P_low = (s-1)²+1, P_mid = s²-s, P_fit = s². N = P/2 throughout.
"""

import math
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)

import bidder_c_native as bidder

N_KEYS = 2000
KEY_PREFIX = b'M2-pow2-'


def f(x):
    return math.sin(math.pi * x)


def population_stats(P):
    vals = [f(k / P) for k in range(P)]
    R = sum(vals) / P
    sigma2 = sum((v - R) ** 2 for v in vals) / P
    return R, sigma2


def fpc_var(N, P, sigma2):
    if N >= P:
        return 0.0
    return sigma2 / N * (P - N) / (P - 1)


def measure(P, N, R, n_keys, key_tag):
    sumsq = 0.0
    for k in range(n_keys):
        key = KEY_PREFIX + key_tag + b'-' + k.to_bytes(8, 'little')
        block = bidder.cipher(P, key)
        s = 0.0
        for i in range(N):
            s += f(block.at(i) / P)
        d = s / N - R
        sumsq += d * d
    return sumsq / n_keys


def run_band(s_list, label):
    print(f'\n=== {label} ===')
    print(f's | factorisation | P_low | r_low | P_mid | r_mid | P_fit | r_fit')
    print('-' * 80)
    rows = []
    band_t0 = time.perf_counter()
    for s in s_list:
        # crude factorisation tag for the table
        n = s
        factors = []
        d = 2
        while d * d <= n:
            while n % d == 0:
                factors.append(d)
                n //= d
            d += 1
        if n > 1:
            factors.append(n)
        fac_str = '·'.join(str(p) for p in factors) if factors else str(s)

        results = {}
        for tag, P in [('low', (s-1)*(s-1)+1),
                       ('mid', max(1, s*s - s)),
                       ('fit', s*s)]:
            N = max(1, P // 2)
            R, sigma2 = population_stats(P)
            t0 = time.perf_counter()
            measured = measure(P, N, R, N_KEYS,
                               f's{s}-{tag}'.encode())
            ideal = fpc_var(N, P, sigma2)
            ratio = measured / ideal if ideal > 0 else float('nan')
            results[tag] = (P, ratio, time.perf_counter() - t0)
        Pl, rl, _ = results['low']
        Pm, rm, _ = results['mid']
        Pf, rf, _ = results['fit']
        print(f'{s:4d} | {fac_str:>12s} | {Pl:5d} | {rl:7.4f} | '
              f'{Pm:5d} | {rm:7.4f} | {Pf:5d} | {rf:7.4f}')
        rows.append((s, fac_str, Pl, rl, Pm, rm, Pf, rf))
    print(f'  -- band: {time.perf_counter() - band_t0:.1f}s')
    return rows


def main():
    overall_t0 = time.perf_counter()
    s_64 = list(range(62, 68))
    s_128 = list(range(126, 131))
    band_64 = run_band(s_64, 'Band: s = 62..67 (covers s=64=2^6)')
    band_128 = run_band(s_128, 'Band: s = 126..130 (covers s=128=2^7)')
    print(f'\nOverall: {time.perf_counter() - overall_t0:.1f}s')

    md_path = os.path.join(HERE, 'm2_power_of_two_results.md')
    with open(md_path, 'w') as md:
        md.write('# M2 Power-of-2 Feistel-domain probe\n\n')
        md.write(f'Generated by `m2_power_of_two.py`. n_keys = '
                 f'{N_KEYS} per cell. Integrand sin(πx). N = P/2.\n\n')
        for label, band in [('s = 62..67 (centred on s=64=2^6)', band_64),
                            ('s = 126..130 (centred on s=128=2^7)', band_128)]:
            md.write(f'## {label}\n\n')
            md.write('| s | factorisation | P_low | ratio | '
                     'P_mid | ratio | P_fit | ratio |\n')
            md.write('|---|---|---|---|---|---|---|---|\n')
            for s, fac_str, Pl, rl, Pm, rm, Pf, rf in band:
                md.write(f'| {s} | {fac_str} | {Pl} | {rl:.4f} | '
                         f'{Pm} | {rm:.4f} | {Pf} | {rf:.4f} |\n')
            md.write('\n')
    print(f'\nWrote {md_path}')


if __name__ == '__main__':
    main()
