"""
use_case_01_stratified_survey.py — §7.1 Stratified survey design.

Substrate-leveraged use case (§3.2 clauses 1–2 do the work; cipher
delivers per-stratum random access). Demonstrates exact per-stratum
counts via per-stratum keyed random access; compares to i.i.d.-
then-post-stratify, which has binomial deviation `O(sqrt(N_total /
(b−1)))`.

Output: replication/use_case_01_results.md.

Run via `.venv/bin/python replication/use_case_01_stratified_survey.py`.
"""

import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)

import bidder_c_native as bidder


B = 10
D = 4
STRATUM_SIZE = B ** (D - 1)  # 1000 at (10, 4)
PANEL_ALPHAS = [0.1, 0.5, 1.0]
N_TRIALS_IID = 1000


def leading_digit(x: int, b: int) -> int:
    while x >= b:
        x //= b
    return x


def bidder_stratified_sample(alpha: float) -> list[int]:
    """Per-stratum keyed prefix; returns realised stratum sizes."""
    n_j = int(alpha * STRATUM_SIZE)
    sizes = []
    for j in range(1, B):
        key = b'use_case_01-stratum-' + j.to_bytes(8, 'little')
        block = bidder.cipher(STRATUM_SIZE, key)
        # Draw n_j keyed prefix samples from stratum j; record only
        # the realised count (the values themselves are streaming).
        for i in range(n_j):
            _ = block.at(i)
        sizes.append(n_j)
    return sizes


def iid_post_stratify_trial(alpha: float, rng: np.random.Generator) -> list[int]:
    n_total = int(alpha * STRATUM_SIZE * (B - 1))
    sample = rng.integers(B ** (D - 1), B ** D, size=n_total)
    sizes = [0] * (B - 1)
    for x in sample:
        sizes[leading_digit(int(x), B) - 1] += 1
    return sizes


def iid_post_stratify_panel(alpha: float, n_trials: int):
    rng = np.random.default_rng(seed=20260502)
    n_total = int(alpha * STRATUM_SIZE * (B - 1))
    target = n_total / (B - 1)
    deviations = []
    means = []
    for _ in range(n_trials):
        sizes = iid_post_stratify_trial(alpha, rng)
        means.append(np.mean(sizes))
        deviations.append(max(abs(s - target) for s in sizes))
    return {
        'n_total': n_total,
        'target': target,
        'mean_size': float(np.mean(means)),
        'mean_max_dev': float(np.mean(deviations)),
        'p99_max_dev': float(np.percentile(deviations, 99)),
        'theoretical_std_per_stratum': math.sqrt(n_total * (1 / (B - 1)) * ((B - 2) / (B - 1))),
    }


def main():
    print('§7.1 Stratified survey design with exact leading-digit strata')
    print(f'  (b, d) = ({B}, {D}); stratum size = b^(d-1) = {STRATUM_SIZE:,}')
    print(f'  Design weights α_j ∈ {PANEL_ALPHAS}')
    print()

    rows = []
    print(f'  {"α":>6} {"N_total":>10} {"BIDDER N_j":>12} {"i.i.d. mean N_j":>17} '
          f'{"i.i.d. max dev (mean)":>23} {"i.i.d. max dev (99th)":>23} '
          f'{"theoretical std":>17}')
    for alpha in PANEL_ALPHAS:
        bidder_sizes = bidder_stratified_sample(alpha)
        iid = iid_post_stratify_panel(alpha, N_TRIALS_IID)
        rows.append({
            'alpha': alpha,
            'n_total': iid['n_total'],
            'bidder_per_stratum': bidder_sizes[0],
            'bidder_max_dev': max(abs(s - bidder_sizes[0]) for s in bidder_sizes),
            'iid_mean_size': iid['mean_size'],
            'iid_mean_max_dev': iid['mean_max_dev'],
            'iid_p99_max_dev': iid['p99_max_dev'],
            'iid_theoretical_std': iid['theoretical_std_per_stratum'],
        })
        print(f'  {alpha:>6.2f} {iid["n_total"]:>10,} '
              f'{bidder_sizes[0]:>12,} '
              f'{iid["mean_size"]:>17.2f} '
              f'{iid["mean_max_dev"]:>23.2f} '
              f'{iid["p99_max_dev"]:>23.2f} '
              f'{iid["theoretical_std_per_stratum"]:>17.2f}')

    # Confirm BIDDER strata are exactly equal-sized.
    print()
    print('BIDDER strata exact-equal across all panels:',
          all(r['bidder_max_dev'] == 0 for r in rows))
    print()

    md_path = os.path.join(HERE, 'use_case_01_results.md')
    with open(md_path, 'w') as fp:
        fp.write('# §7.1 — Stratified survey design with exact leading-digit strata\n\n')
        fp.write('Generated by `replication/use_case_01_stratified_survey.py`. '
                'Substrate-leveraged use case (§3.2 clauses 1–2 do the '
                'work; the cipher delivers per-stratum keyed random '
                'access).\n\n')
        fp.write(f'`(b, d) = ({B}, {D})`; stratum size '
                 f'`b^(d-1) = {STRATUM_SIZE:,}`. Proportional design '
                 f'weights `α_j ∈ {PANEL_ALPHAS}` per stratum; total '
                 f'sample size `N_total = α · (b−1) · b^(d-1)`. '
                 f'BIDDER row: per-stratum count is exactly '
                 f'`⌊α · b^(d-1)⌋`. i.i.d. row: '
                 f'`{N_TRIALS_IID:,}` trials of post-stratification '
                 f'on uniform i.i.d. samples from the block.\n\n')

        fp.write('## Realised stratum sizes\n\n')
        fp.write('| α | N_total | BIDDER per-stratum (exact) | BIDDER max dev | '
                 'i.i.d. mean per-stratum | i.i.d. mean max dev | '
                 'i.i.d. 99th-pct max dev | theoretical std (per stratum) |\n')
        fp.write('|---|---|---|---|---|---|---|---|\n')
        for r in rows:
            fp.write(f'| {r["alpha"]:.2f} | {r["n_total"]:,} | '
                     f'**{r["bidder_per_stratum"]:,}** | '
                     f'{r["bidder_max_dev"]} | '
                     f'{r["iid_mean_size"]:.2f} | '
                     f'{r["iid_mean_max_dev"]:.2f} | '
                     f'{r["iid_p99_max_dev"]:.2f} | '
                     f'{r["iid_theoretical_std"]:.2f} |\n')
        fp.write('\n')

        fp.write('## Reading\n\n')
        fp.write('- **BIDDER row.** Per-stratum count is `⌊α · b^(d-1)⌋` '
                 'exactly across all 9 strata; max deviation = 0. The '
                 'substrate guarantee (§3.2 clause 1) is structural — '
                 'exact at any α; cipher delivers a keyed prefix of '
                 'the per-stratum permutation, streaming and '
                 'reproducible.\n')
        fp.write('- **i.i.d.-then-post-stratify row.** Mean per-stratum '
                 'count tracks `N_total / (b−1)` as expected; max '
                 'deviation across 9 strata grows as '
                 '`O(sqrt(N_total · (b−2)/(b−1)²))`. At `α = 1.0` '
                 '(N_total = 9,000), the 99th-percentile max '
                 'deviation across 1000 trials is the order of one '
                 '99th-percentile binomial deviate from the mean of '
                 '9 independent strata.\n')
        fp.write('- **Headline payoff.** Exact per-stratum counts let '
                 'stratified-sample variance estimators apply design '
                 'weights `α_j` directly, without post-hoc adjustment '
                 'for realised stratum sizes — the i.i.d.-then-post-'
                 'stratify approach would otherwise carry a '
                 '`O(sqrt(N_total))` correction.\n')
        fp.write('- **Use something else when** the application '
                 'tolerates `O(sqrt(N_total / k))` deviation in '
                 'stratum sizes; standard proportional sampling with '
                 'post-stratification is simpler.\n')

    print(f'Wrote {md_path}')


if __name__ == '__main__':
    main()
