"""
use_case_04_fpe.py — §7.4 Format-preserving permutation of small-P.

Cipher-leveraged use case (§4.4 contract is what's load-bearing).
Demonstrates the headline thing BIDDER does: a keyed reproducible
bijection of `[0, P)` for arbitrary `P`. Verifies bijectivity at
small `P` by exhaustive enumeration; renders the §7.4 capability
matrix and three-workload throughput row from M3 + D1 + D4 outputs.

Output: replication/use_case_04_results.md.

Run via `.venv/bin/python replication/use_case_04_fpe.py`.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)

import bidder_c_native as bidder


def verify_bijection(P: int, key: bytes) -> bool:
    block = bidder.cipher(P, key)
    seen = set()
    for i in range(P):
        y = block.at(i)
        if not (0 <= y < P):
            return False
        if y in seen:
            return False
        seen.add(y)
    return len(seen) == P


def determinism_check(P: int, key: bytes) -> bool:
    a = [bidder.cipher(P, key).at(i) for i in range(P)]
    b = [bidder.cipher(P, key).at(i) for i in range(P)]
    return a == b


def main():
    print('§7.4 Format-preserving permutation of small-P domain')
    print()

    panel = [11, 100, 257, 1000, 9973, 65537]  # mix of primes, powers, and composites
    rows = []
    print(f'  {"P":>10}  {"bijection":>10}  {"determinism":>12}')
    for P in panel:
        key = b'use_case_04-key-' + P.to_bytes(8, 'little')
        bij = verify_bijection(P, key)
        det = determinism_check(P, key)
        rows.append({'P': P, 'bijection': bij, 'determinism': det})
        print(f'  {P:>10,}  {"OK" if bij else "FAIL":>10}  {"OK" if det else "FAIL":>12}')

    all_ok = all(r['bijection'] and r['determinism'] for r in rows)
    print()
    print('All bijection + determinism checks pass.' if all_ok else 'FAILURES PRESENT.')

    md_path = os.path.join(HERE, 'use_case_04_results.md')
    with open(md_path, 'w') as f:
        f.write('# §7.4 — Format-preserving permutation of small-P domain\n\n')
        f.write('Generated by `replication/use_case_04_fpe.py`. '
                'Cipher-leveraged use case; absorbs the head-to-head '
                'comparison from the (now folded) §8.\n\n')

        f.write('## Bijection + determinism check\n\n')
        f.write('Exhaustive enumeration at small `P` of `bidder.cipher.at(i)` '
                'over `i = 0, …, P-1`, plus a determinism check (same key + '
                '`P` → same permutation across constructions).\n\n')
        f.write('| P | bijection | determinism |\n')
        f.write('|---|---|---|\n')
        for r in rows:
            f.write(f'| {r["P"]:,} | {"OK" if r["bijection"] else "FAIL"} | '
                    f'{"OK" if r["determinism"] else "FAIL"} |\n')
        f.write('\n')

        f.write('## Capability matrix (from M3)\n\n')
        f.write('Five axes, six rows. The headline finding is *qualitative*: '
                'BIDDER is the only comparator with all of {keyed, '
                'reproducible, streaming/random-access, arbitrary `P`, '
                'zero deps}.\n\n')
        f.write('| comparator | keyed | reproducible | streaming | arbitrary P | extra deps |\n')
        f.write('|---|---|---|---|---|---|\n')
        f.write('| BIDDER (cipher) | yes | yes | yes (random-access) | yes (P ≤ 2³² − 1) | none (~300 lines C) |\n')
        f.write('| numpy.random.permutation | via seed | yes | no (in-memory) | yes | numpy |\n')
        f.write('| random.shuffle | via seed | yes | no (in-memory) | yes | stdlib only |\n')
        f.write('| sort-by-iid-key | via seed | yes | no (sort is global) | yes | numpy |\n')
        f.write('| i.i.d. (replacement) | via seed | yes | yes | yes | numpy or stdlib |\n')
        f.write('| FF1 / FF3-1 (D1) | yes | yes | yes (random-access) | yes | AES + FPE library |\n')
        f.write('\n')

        f.write('## Throughput across three workloads (§6.4 taxonomy)\n\n')
        f.write('Workloads measure different things; rows tagged so '
                'readers compare like to like.\n\n')
        f.write('| workload | BIDDER | FF1 (AES-128) | numpy.random.permutation | random.shuffle | sort-by-iid-key |\n')
        f.write('|---|---|---|---|---|---|\n')
        f.write('| (1) single random-access call (M4) | ~940 ns/call (cipher) | n/a | n/a | n/a | n/a |\n')
        f.write('| (2) materialise full perm at P = 1M (M3 + D1) | 5,366 ns/elem | 100,202 ns/elem | 268 ns/elem | 1,889 ns/elem | 407 ns/elem |\n')
        f.write('| (3) C-direct kernel (D4) | 38 ns/call (Feistel) | not benchmarked C-direct | n/a | n/a | n/a |\n')
        f.write('\n')
        f.write('*FF1 / BIDDER through the same Python wrapper:* FF1 is '
                '~19× heavier at P = 1M, ~24× at P = 100k, ~29× at '
                'P = 10k (cycle-walking ratio higher at smaller P). FF1 '
                'lands at FPC ratio ~0.92 at the M2 cells; BIDDER at '
                '6.8–32× the ideal. The trade is **~25× per-call cost '
                'for ~20× tighter FPC**.\n\n')

        f.write('## Reading\n\n')
        f.write('- **Headline.** BIDDER is the only comparator with all '
                'of {keyed, reproducible, streaming, arbitrary `P`, zero '
                'deps}. The C-direct kernel is sub-µs (38 ns/call '
                'Feistel); through the Python wrapper, ~5 µs/elem when '
                'materialising the full permutation. FF1 / FF3-1 with '
                'AES is the right choice when cryptographic-strength '
                'PRP and tight FPC realisation are required and ~20× '
                'higher per-call cost is acceptable.\n')
        f.write('- **Use case scope.** Anonymising customer IDs in '
                '`[0, 10⁶)` for a deterministic test corpus; randomising '
                'row order in a finite dataset for staged processing '
                'where the same key reproduces the order on re-run; '
                'deterministically permuting a fixed-size token '
                'vocabulary across runs of an experiment. None of these '
                'are adversarial settings; cryptographic-strength PRP '
                'is not load-bearing.\n')
        f.write('- **Comparator notes.** `numpy.random.permutation` '
                'wins workload (2) when the dataset fits in memory; '
                'FF1 wins on FPC tightness and PRP strength at higher '
                'per-call cost; `secrets.SystemRandom().shuffle()` is '
                'the right tool when CSPRNG-grade unguessability '
                'matters and reproducibility doesn\'t.\n')


if __name__ == '__main__':
    main()
