"""
use_case_06_variance_mc.py — §7.6 variance-controlled Monte Carlo.

Demonstrates: at `N = P` the structural Riemann-sum identity (§4.4)
gives prefix-mean variance machine-ε across keys; at `N < P` the
variance follows the FPC shape `σ²/N · (P − N)/(P − 1)` (§4.5) up
to BIDDER's measured realisation gap (M2). i.i.d.-with-replacement
baseline never benefits from the FPC.

Single (P, f) cell with multiple N values, three series:
  - BIDDER measured (n_keys keyed permutations, prefix-mean
    variance about R)
  - Ideal-permutation FPC theory (closed form)
  - i.i.d. baseline (σ²/N, never zero)

Output: replication/use_case_06_results.md.

Run via `.venv/bin/python replication/use_case_06_variance_mc.py`.
"""

import math
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)

import bidder_c_native as bidder


P = 2000
N_KEYS = 200
N_VALUES = [200, 500, 1000, 1500, 1800, 1999, 2000]


def f(x: float) -> float:
    return math.sin(math.pi * x)


def population_stats(P: int):
    vals = [f(k / P) for k in range(P)]
    R = sum(vals) / P
    sigma2 = sum((v - R) ** 2 for v in vals) / P
    return R, sigma2


def fpc_var(N: int, P: int, sigma2: float) -> float:
    if N >= P:
        return 0.0
    return sigma2 / N * (P - N) / (P - 1)


def iid_baseline_var(N: int, sigma2: float) -> float:
    """Variance of an i.i.d.-with-replacement estimator at sample N."""
    return sigma2 / N


def measure_bidder_variance(P: int, N: int, R: float, n_keys: int):
    sumsq = 0.0
    for k in range(n_keys):
        key = b'use_case_06-key-' + k.to_bytes(8, 'little')
        block = bidder.cipher(P, key)
        prefix_sum = 0.0
        for i in range(N):
            prefix_sum += f(block.at(i) / P)
        prefix_mean = prefix_sum / N
        d = prefix_mean - R
        sumsq += d * d
    return sumsq / n_keys


def main():
    R, sigma2 = population_stats(P)
    print(f'§7.6 variance-controlled Monte Carlo')
    print(f'  P = {P}, f = sin(πx), σ² = {sigma2:.6f}, R = {R:.6f}')
    print(f'  n_keys = {N_KEYS} per N')
    print()

    print(f'  {"N":>6} {"N/P":>6} {"BIDDER var":>14} {"ideal FPC var":>14} '
          f'{"i.i.d. var":>14} {"BIDDER/ideal":>13}')
    rows = []
    for N in N_VALUES:
        bidder_var = measure_bidder_variance(P, N, R, N_KEYS)
        ideal = fpc_var(N, P, sigma2)
        iid = iid_baseline_var(N, sigma2)
        ratio = bidder_var / ideal if ideal > 0 else float('inf')
        rows.append({
            'N': N,
            'N_over_P': N / P,
            'bidder_var': bidder_var,
            'ideal_var': ideal,
            'iid_var': iid,
            'ratio': ratio,
        })
        ratio_str = f'{ratio:>13.3f}' if ideal > 0 else f'{"machine-ε at N=P":>13}'
        print(f'  {N:>6} {N/P:>6.2f} {bidder_var:>14.3e} {ideal:>14.3e} '
              f'{iid:>14.3e} {ratio_str}')
    print()

    md_path = os.path.join(HERE, 'use_case_06_results.md')
    with open(md_path, 'w') as fp:
        fp.write('# §7.6 — Variance-controlled Monte Carlo with known FPC\n\n')
        fp.write('Generated by `replication/use_case_06_variance_mc.py`. '
                'Substrate-and-cipher use case (§4.4 endpoint invariance + '
                '§4.5 FPC shape both load-bearing).\n\n')
        fp.write(f'`P = {P}`, integrand `f = sin(πx)` sampled at `f(k/P)` '
                f'for `k ∈ [0, P)`. `σ² = {sigma2:.6f}` (population variance '
                f'about the Riemann sum `R = {R:.6f}`). `n_keys = {N_KEYS}` '
                f'BIDDER permutations per `N`.\n\n')

        fp.write('## Variance-vs-N panel\n\n')
        fp.write('Three series: BIDDER measured, ideal-permutation FPC '
                '(closed form `σ²/N · (P-N)/(P-1)`), i.i.d.-with-'
                'replacement baseline (`σ²/N`).\n\n')
        fp.write('| N | N/P | BIDDER measured Var | ideal FPC Var | i.i.d. Var | BIDDER / ideal |\n')
        fp.write('|---|---|---|---|---|---|\n')
        for r in rows:
            ratio_cell = f'{r["ratio"]:.3f}' if r['ideal_var'] > 0 else 'machine-ε at N=P'
            fp.write(f'| {r["N"]} | {r["N_over_P"]:.2f} | '
                     f'{r["bidder_var"]:.3e} | '
                     f'{r["ideal_var"]:.3e} | '
                     f'{r["iid_var"]:.3e} | '
                     f'{ratio_cell} |\n')
        fp.write('\n')

        end_row = rows[-1]
        max_ratio_row = max((r for r in rows if r['ideal_var'] > 0),
                             key=lambda r: r['ratio'])

        fp.write('## Reading\n\n')
        fp.write(f'- **Endpoint identity (§4.4) verified.** At `N = P = '
                 f'{P}`, BIDDER\'s measured variance is '
                 f'`{end_row["bidder_var"]:.3e}` (machine-ε; the '
                 f'remaining bits are floating-point round-off in the '
                 f'sum). The ideal FPC at `N = P` is exactly zero. '
                 f'i.i.d.-with-replacement at `N = P` is `σ²/P = '
                 f'{end_row["iid_var"]:.3e}` — never zero. The '
                 f'structural Riemann-sum identity is what makes BIDDER '
                 f'exact at the endpoint; the cipher\'s PRP quality is '
                 f'not invoked at `N = P`.\n')
        fp.write(f'- **FPC shape at `N < P` (§4.5).** BIDDER\'s '
                 f'measured variance follows the FPC shape with a '
                 f'realisation gap. Worst BIDDER-vs-ideal ratio in this '
                 f'panel: `{max_ratio_row["ratio"]:.3f}` at `N = '
                 f'{max_ratio_row["N"]}`. The shape is U-shaped in '
                 f'`N/P`: peak around `N = P/2`, smaller at the '
                 f'extremes. Magnitude scales with `P` (M2\'s grid '
                 f'shows ~32× at P = 10000).\n')
        fp.write('- **i.i.d. baseline.** Tracks `σ²/N` across the panel; '
                 'never benefits from the FPC; lands at `σ²/P` at '
                 '`N = P`. Choosing BIDDER over i.i.d. with replacement '
                 'is choosing a known closed-form variance (FPC + '
                 'realisation gap) over a strictly larger one.\n')
        fp.write('- **Comparator note.** FF1 with AES (D1) lands at '
                 'FPC ratio ~0.92 at the same M2 cells where BIDDER is '
                 '6.8–32×; FF1 is the right tool when FPC tightness '
                 'within ~10% of ideal is required, at ~19–29× higher '
                 'per-call cost than BIDDER.\n')

    print(f'Wrote {md_path}')


if __name__ == '__main__':
    main()
