"""
use_case_02_prefix_imbalance.py -- order-sensitive Benford-null diagnostic.

Endpoint leading-digit exactness is a multiset property. This script
measures whether the order itself leaks lexicographic structure by tracking
the worst finite-population standardized leading-digit imbalance over all
prefixes of an exact-balanced block.

Output: replication/use_case_02_prefix_imbalance_results.md.
"""

import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, REPO)

import bidder_c_native as bidder


BASE = 10
DIGIT_CLASS = 4
PER_DIGIT = BASE ** (DIGIT_CLASS - 1)
N_DIGITS = BASE - 1
PERIOD = N_DIGITS * PER_DIGIT

N_RANDOM = 256
N_BIDDER_KEYS = 64
RNG_SEED = 20260503
KEY_PREFIX = b"bidder-prefix-imbalance-v1"


def lexicographic_labels():
    return np.repeat(np.arange(1, BASE, dtype=np.int16), PER_DIGIT)


def bidder_labels(key: bytes):
    block = bidder.cipher(PERIOD, key)
    indices = np.fromiter((int(block.at(i)) for i in range(PERIOD)), dtype=np.int64, count=PERIOD)
    return (indices // PER_DIGIT + 1).astype(np.int16)


def random_labels(rng):
    return (rng.permutation(PERIOD) // PER_DIGIT + 1).astype(np.int16)


def prefix_imbalance(labels):
    t = np.arange(1, PERIOD, dtype=np.float64)
    p = 1.0 / N_DIGITS
    expected = t * p
    variance = t * p * (1.0 - p) * (PERIOD - t) / (PERIOD - 1)
    sd = np.sqrt(variance)

    z_by_digit = np.empty((N_DIGITS, PERIOD - 1), dtype=np.float64)
    for row, digit in enumerate(range(1, BASE)):
        counts = np.cumsum(labels == digit, dtype=np.int32)[:-1].astype(np.float64)
        z_by_digit[row] = np.abs(counts - expected) / sd

    path = z_by_digit.max(axis=0)
    digit_at_prefix = z_by_digit.argmax(axis=0) + 1
    i = int(path.argmax())

    return {
        "dmax": float(path[i]),
        "t_at_max": i + 1,
        "digit_at_max": int(digit_at_prefix[i]),
        "endpoint_counts": np.bincount(labels, minlength=BASE)[1:BASE],
    }


def quantiles(values):
    q05, q50, q95, q99 = np.percentile(values, [5, 50, 95, 99])
    return {
        "min": float(values.min()),
        "p05": float(q05),
        "median": float(q50),
        "p95": float(q95),
        "p99": float(q99),
        "max": float(values.max()),
    }


def main():
    rng = np.random.default_rng(RNG_SEED)

    lex = prefix_imbalance(lexicographic_labels())
    bid = prefix_imbalance(bidder_labels(KEY_PREFIX + b":000"))

    bidder_dmax = []
    for i in range(N_BIDDER_KEYS):
        key = KEY_PREFIX + f":{i:03d}".encode("ascii")
        bidder_dmax.append(prefix_imbalance(bidder_labels(key))["dmax"])
    bidder_dmax = np.array(bidder_dmax)

    random_dmax = []
    for _ in range(N_RANDOM):
        random_dmax.append(prefix_imbalance(random_labels(rng))["dmax"])
    random_dmax = np.array(random_dmax)

    assert np.all(lex["endpoint_counts"] == PER_DIGIT)
    assert np.all(bid["endpoint_counts"] == PER_DIGIT)
    assert bid["dmax"] < 0.2 * lex["dmax"]
    assert bidder_dmax.max() < 0.2 * lex["dmax"]

    bidder_q = quantiles(bidder_dmax)
    random_q = quantiles(random_dmax)

    print("Prefix imbalance diagnostic")
    print(f"  block: [{PER_DIGIT}, {BASE * PER_DIGIT - 1}]")
    print(f"  period: {PERIOD}; per-digit count: {PER_DIGIT}")
    print(f"  lexicographic Dmax: {lex['dmax']:.3f}")
    print(f"  BIDDER key 0 Dmax: {bid['dmax']:.3f}")
    print(f"  BIDDER keys median/p95/max: {bidder_q['median']:.3f} / {bidder_q['p95']:.3f} / {bidder_q['max']:.3f}")
    print(f"  random median/p95/max: {random_q['median']:.3f} / {random_q['p95']:.3f} / {random_q['max']:.3f}")

    md_path = os.path.join(HERE, "use_case_02_prefix_imbalance_results.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("# Prefix imbalance diagnostic\n\n")
        f.write("Generated by `replication/use_case_02_prefix_imbalance.py`.\n\n")
        f.write("Endpoint leading-digit exactness is a multiset property. This diagnostic ")
        f.write("uses the exact-balanced integer block `[1000, 9999]`, with exactly ")
        f.write("1000 values at each leading digit, and measures the maximum finite-")
        f.write("population standardized leading-digit deviation over all prefixes.\n\n")

        f.write("## Parameters\n\n")
        f.write(f"- base: `{BASE}`\n")
        f.write(f"- digit class: `{DIGIT_CLASS}`\n")
        f.write(f"- period: `{PERIOD}`\n")
        f.write(f"- per-leading-digit endpoint count: `{PER_DIGIT}`\n")
        f.write(f"- BIDDER keys: `{N_BIDDER_KEYS}`\n")
        f.write(f"- random permutations: `{N_RANDOM}`\n")
        f.write(f"- random seed: `{RNG_SEED}`\n\n")

        f.write("## Worst prefix imbalance\n\n")
        f.write("| order family | Dmax | prefix t | digit at max |\n")
        f.write("|---|---:|---:|---:|\n")
        f.write(f"| lexicographic | {lex['dmax']:.3f} | {lex['t_at_max']} | {lex['digit_at_max']} |\n")
        f.write(f"| BIDDER key 0 | {bid['dmax']:.3f} | {bid['t_at_max']} | {bid['digit_at_max']} |\n\n")

        f.write("## Ensemble summaries\n\n")
        f.write("| ensemble | min | p05 | median | p95 | p99 | max |\n")
        f.write("|---|---:|---:|---:|---:|---:|---:|\n")
        f.write(
            f"| BIDDER keys | {bidder_q['min']:.3f} | {bidder_q['p05']:.3f} | "
            f"{bidder_q['median']:.3f} | {bidder_q['p95']:.3f} | "
            f"{bidder_q['p99']:.3f} | {bidder_q['max']:.3f} |\n"
        )
        f.write(
            f"| random permutations | {random_q['min']:.3f} | {random_q['p05']:.3f} | "
            f"{random_q['median']:.3f} | {random_q['p95']:.3f} | "
            f"{random_q['p99']:.3f} | {random_q['max']:.3f} |\n\n"
        )

        f.write("## Endpoint counts\n\n")
        f.write(f"- lexicographic: `{lex['endpoint_counts'].tolist()}`\n")
        f.write(f"- BIDDER key 0: `{bid['endpoint_counts'].tolist()}`\n\n")

        f.write("## Reading\n\n")
        f.write("- **Endpoint exactness alone is not enough.** Lexicographic order has ")
        f.write("the same terminal counts as any permutation of the block, but its ")
        f.write("worst prefix imbalance is `94.863` at the first digit boundary.\n")
        f.write("- **BIDDER removes the enumeration pathology.** The fixed paper key gives ")
        f.write("`Dmax = 7.520`, and all 64 checked BIDDER keys remain below 20% of the ")
        f.write("lexicographic value.\n")
        f.write("- **BIDDER is not being claimed as a uniformly random permutation.** ")
        f.write("Across the checked keys its prefix imbalance is measurably larger than ")
        f.write("the random-permutation baseline. The claim is narrower: keyed order ")
        f.write("breaks the lexicographic leading-digit run while retaining exact endpoint ")
        f.write("composition and reproducibility.\n")

    print(f"Wrote {md_path}")


if __name__ == "__main__":
    main()
